/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#2a2a2a',
        'on-background': '#e5e2e1',
        'on-tertiary-fixed': '#301400',
        'surface': '#131313',
        'tertiary-fixed': '#ffdcc5',
        'surface-tint': '#c0c1ff',
        'on-secondary': '#313030',
        'secondary-fixed': '#e5e2e1',
        'on-error': '#690005',
        'secondary': '#c8c6c5',
        'tertiary': '#ffb783',
        'on-surface-variant': '#c7c4d7',
        'on-secondary-fixed-variant': '#474646',
        'on-tertiary-container': '#452000',
        'on-primary': '#1000a9',
        'surface-container-lowest': '#0e0e0e',
        'primary': '#c0c1ff',
        'on-primary-container': '#0d0096',
        'inverse-on-surface': '#313030',
        'surface-container': '#201f1f',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#353534',
        'surface-dim': '#131313',
        'primary-fixed': '#e1e0ff',
        'tertiary-container': '#d97721',
        'outline-variant': '#464554',
        'background': '#131313',
        'inverse-primary': '#494bd6',
        'outline': '#908fa0',
        'on-surface': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'primary-fixed-dim': '#c0c1ff',
        'primary-container': '#8083ff',
        'inverse-surface': '#e5e2e1',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-secondary-container': '#bab8b7',
        'surface-variant': '#353534',
        'secondary-container': '#4a4949',
        'on-secondary-fixed': '#1c1b1b',
        'on-primary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#703700',
        'surface-bright': '#3a3939',
        'tertiary-fixed-dim': '#ffb783',
        'surface-container-low': '#1c1b1b',
        'on-tertiary': '#4f2500',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '240px',
        'element-gap': '8px',
        'unit': '4px',
        'gutter': '16px',
        'container-padding': '24px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
