import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Sidebar from '../../components/Sidebar'
import { generateMatches, approveMatch } from '../../services/matching.service'

const C = { red: '#ef4444', amber: '#f59e0b', green: '#22c55e', blue: '#60a5fa' }

const MOCK = [
  {
    startup_id: 's1',
    startup: {
      company_name: 'CareLoop',
      initials: 'CL',
      sector: 'Healthtech · MVP stage',
      description: 'Remote patient monitoring platform for clinics in Malaysia. Real-time vitals tracking, alerts, and chronic care plans — moving toward MOH pilot approval.',
      country: 'Malaysia', stage: 'MVP', founded: '2024', teamSize: '5',
      support: 'Regulatory · Clinical partnerships',
      tags: ['healthtech', 'remote monitoring', 'b2b clinical'],
    },
    suggestions: [
      {
        mentor_id: 'm1',
        mentor: { full_name: 'Nurul Huda', role_meta: 'ex-KKM consultant · 8 yrs · Malaysia' },
        tags: ['healthtech', 'regulatory', 'clinical partnerships', 'healthcare ops'],
        reasoning: "Nurul's regulatory experience at KKM directly addresses CareLoop's MOH pilot path. The DNA library flags this exact pairing pattern — a regulatory-experienced mentor with a healthtech founder reaching for pilot approval — as one of the highest-yield matches in past Malaysian cohorts.",
        ref: 'Generated by Gemini Flash · referencing 2 DNA blueprints',
        embedding_score: 0.91, dna_score: 0.88, combined_score: 0.90, isBest: true,
      },
      {
        mentor_id: 'm2',
        mentor: { full_name: 'Priya Nair', role_meta: 'Head of Product · Grab · 10 yrs' },
        tags: ['saas / b2b', 'product strategy', 'go-to-market'],
        reasoning: "Strong product strategy fit for CareLoop's B2B clinical motion. Less regulatory depth than candidate #1, but DNA shows Priya's GTM frameworks transfer well when target persona is well-defined — which CareLoop has.",
        ref: 'Generated by Gemini Flash · referencing 1 DNA blueprint',
        embedding_score: 0.79, dna_score: 0.72, combined_score: 0.76, isBest: false,
      },
      {
        mentor_id: 'm3',
        mentor: { full_name: 'Ahmad Razif', role_meta: 'VP · Maybank · 14 yrs' },
        tags: ['fintech', 'fundraising', 'investor relations'],
        reasoning: 'Excellent fundraising network but the industry overlap is weak. CareLoop will need clinical guidance well before its first raise. Consider as a secondary mentor closer to seed round.',
        ref: 'Generated by Gemini Flash · no matching DNA blueprints',
        embedding_score: 0.62, dna_score: 0.34, combined_score: 0.51, isBest: false,
      },
    ],
  },
]

function scoreColor(s) {
  if (s >= 0.80) return C.green
  if (s >= 0.60) return C.amber
  return C.red
}

function initials(name) {
  return (name ?? '?').split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase()
}

const Tag = ({ label }) => (
  <span className="text-[11px] px-2 py-0.5 rounded-full border"
        style={{ background: 'rgba(255,255,255,0.04)', borderColor: '#232327', color: '#8a8a92' }}>
    {label}
  </span>
)

export default function MatchExplorer() {
  const { programmeId } = useParams()
  const navigate = useNavigate()
  const [results, setResults] = useState(MOCK)
  const [current, setCurrent] = useState(0)
  const [approving, setApproving] = useState(null)

  useEffect(() => {
    if (programmeId && programmeId !== 'demo') {
      generateMatches(programmeId).then(d => { if (d?.length) setResults(d) }).catch(() => {})
    }
  }, [programmeId])

  const row = results[current]
  if (!row) return null

  const handleApprove = async (mentorId, suggestion) => {
    setApproving(mentorId)
    try {
      await approveMatch(programmeId, { startup_id: row.startup_id, mentor_id: mentorId, ...suggestion })
      if (current < results.length - 1) setCurrent(c => c + 1)
      else navigate('/admin/dashboard')
    } catch (err) {
      console.error(err)
    } finally {
      setApproving(null)
    }
  }

  const cardBg = { background: 'linear-gradient(180deg, #18181c 0%, #131316 100%)' }
  const eyebrow = 'text-[11px] text-[#5b5b62] tracking-[0.24em] uppercase'
  const totalStartups = results.length

  return (
    <div className="min-h-screen" style={{ background: '#0b0b0c', color: '#ededee', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <div className="ds-bg" />
      <div className="ds-grid" />
      <Sidebar />

      <main className="ml-[240px] min-h-screen relative z-10 p-10 pt-12 page-enter">

        {/* Page header */}
        <header className="flex items-start justify-between mb-6">
          <div>
            <div className={`${eyebrow} mb-2`}>⭐ AI matching · Cradle CIP 2026</div>
            <h1 className="font-fraunces font-light text-[#ededee] m-0 leading-tight" style={{ fontSize: 'clamp(28px, 3vw, 40px)', letterSpacing: '-0.03em' }}>
              Match Explorer
            </h1>
            <p className="text-[14px] text-[#8a8a92] mt-2 m-0">
              Reviewing AI suggestions for <strong className="text-[#ededee]">{row.startup.company_name}</strong>.
              Top 3 ranked by <span className="font-mono text-[#8a8a92]">0.6 × embedding + 0.4 × DNA</span>.
            </p>
          </div>
          <div className="flex items-center gap-3 flex-shrink-0 ml-8">
            <button
              onClick={() => setCurrent(c => Math.max(0, c - 1))}
              disabled={current === 0}
              className="h-9 px-4 rounded-full border border-[#2c2c32] text-[#8a8a92] hover:text-[#ededee] hover:border-[#3a3a40] text-[13px] font-medium flex items-center gap-2 transition-colors cursor-pointer bg-transparent disabled:opacity-30"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
              Previous
            </button>
            <button
              onClick={() => setCurrent(c => Math.min(results.length - 1, c + 1))}
              disabled={current === results.length - 1}
              className="h-9 px-4 rounded-full border border-[#2c2c32] text-[#8a8a92] hover:text-[#ededee] hover:border-[#3a3a40] text-[13px] font-medium flex items-center gap-2 transition-colors cursor-pointer bg-transparent disabled:opacity-30"
            >
              Next
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
            </button>
          </div>
        </header>

        {/* Progress pills */}
        <div className="mb-6">
          <div className="flex justify-between text-[12px] text-[#5b5b62] mb-2">
            <span>Startup {current + 1} of {totalStartups}</span>
            <span>{Math.round(((current + 1) / totalStartups) * 100)}% reviewed</span>
          </div>
          <div className="flex gap-1.5">
            {Array.from({ length: totalStartups }).map((_, i) => (
              <div
                key={i}
                className="flex-1 h-1 rounded-full transition-colors duration-300"
                style={{ background: i <= current ? '#ededee' : '#232327' }}
              />
            ))}
          </div>
        </div>

        {/* Match layout: startup pane + candidates */}
        <div className="grid gap-6" style={{ gridTemplateColumns: '360px 1fr', alignItems: 'start' }}>

          {/* Startup pane */}
          <aside style={{ position: 'sticky', top: '24px' }}>
            <div className="rounded-2xl border border-[#232327] p-[22px] flex flex-col gap-5" style={cardBg}>
              {/* Avatar + name */}
              <div className="flex items-center gap-4">
                <div
                  className="w-[76px] h-[76px] rounded-[18px] border border-[#2c2c32] flex items-center justify-center font-fraunces font-normal text-[26px] text-[#ededee] flex-shrink-0"
                  style={{ background: 'linear-gradient(135deg, #3a3a40, #1d1d21)' }}
                >
                  {row.startup.initials}
                </div>
                <div>
                  <div className="text-[18px] font-medium text-[#ededee]">{row.startup.company_name}</div>
                  <div className="text-[12.5px] text-[#8a8a92] mt-0.5">{row.startup.sector}</div>
                </div>
              </div>

              {/* Description */}
              <div className="text-[13px] text-[#8a8a92] leading-relaxed p-3.5 rounded-xl border border-[#232327]" style={{ background: '#0f0f12' }}>
                {row.startup.description}
              </div>

              {/* Field rows */}
              <div>
                {[
                  { k: 'Country', v: row.startup.country },
                  { k: 'Stage', v: row.startup.stage },
                  { k: 'Founded', v: row.startup.founded },
                  { k: 'Team size', v: row.startup.teamSize },
                  { k: 'Support needed', v: row.startup.support },
                ].map(f => (
                  <div key={f.k} className="flex justify-between gap-4 py-2.5 border-b border-[#232327] last:border-b-0 text-[13px]">
                    <span className="text-[#8a8a92]">{f.k}</span>
                    <span className="text-[#ededee] text-right">{f.v}</span>
                  </div>
                ))}
              </div>

              {/* Tags */}
              <div>
                <div className={`${eyebrow} mb-2`}>Tags</div>
                <div className="flex gap-1.5 flex-wrap">
                  {row.startup.tags.map(t => <Tag key={t} label={t} />)}
                </div>
              </div>
            </div>

            {/* Override note */}
            <div className="mt-3.5 p-4 rounded-2xl text-[12px] text-[#5b5b62] leading-relaxed" style={{ border: '1px dashed #2c2c32' }}>
              <strong className="text-[#ededee] font-medium">Override</strong> — none of these fit?{' '}
              <a href="#" className="text-[#8a8a92] underline" style={{ textDecorationColor: '#3a3a40', textUnderlineOffset: '2px' }}>
                Search the full mentor pool →
              </a>
            </div>
          </aside>

          {/* Candidates */}
          <section className="flex flex-col gap-3.5">
            {row.suggestions.map((s, idx) => {
              const rank = idx + 1
              const color = scoreColor(s.combined_score)
              const ini = initials(s.mentor.full_name)

              return (
                <article
                  key={s.mentor_id}
                  className="rounded-2xl border p-[22px] relative overflow-hidden transition-colors duration-200"
                  style={{
                    ...cardBg,
                    borderColor: s.isBest ? '#3a3a40' : '#232327',
                  }}
                  onMouseEnter={e => !s.isBest && (e.currentTarget.style.borderColor = '#3a3a40')}
                  onMouseLeave={e => !s.isBest && (e.currentTarget.style.borderColor = '#232327')}
                >
                  {/* Top-pick left accent bar */}
                  {s.isBest && (
                    <div className="absolute left-0 top-0 bottom-0 w-[3px]" style={{ background: `linear-gradient(180deg, #ededee, ${C.blue})` }} />
                  )}

                  <div className="grid gap-[18px]" style={{ gridTemplateColumns: 'auto 1fr auto', alignItems: 'flex-start' }}>
                    {/* Rank */}
                    <div
                      className="w-[38px] h-[38px] rounded-full border flex items-center justify-center font-fraunces text-[18px] flex-shrink-0"
                      style={s.isBest
                        ? { background: '#ededee', color: '#0b0b0c', borderColor: '#ededee' }
                        : { background: 'rgba(0,0,0,0.2)', color: '#8a8a92', borderColor: '#2c2c32' }
                      }
                    >
                      {rank}
                    </div>

                    {/* Body */}
                    <div className="min-w-0">
                      {/* Name row */}
                      <div className="flex items-center gap-2.5 flex-wrap">
                        <span className="text-[17px] font-medium text-[#ededee]">{s.mentor.full_name}</span>
                        <span className="text-[13px] text-[#8a8a92]">· {s.mentor.role_meta}</span>
                        {s.isBest && (
                          <span className="text-[10px] tracking-[0.2em] uppercase font-medium px-2 py-0.5 rounded-full" style={{ background: '#ededee', color: '#0b0b0c' }}>
                            Top pick
                          </span>
                        )}
                      </div>

                      {/* Tags */}
                      <div className="flex gap-1.5 flex-wrap mt-2.5">
                        {s.tags.map(t => <Tag key={t} label={t} />)}
                      </div>

                      {/* Reasoning */}
                      <div
                        className="mt-4 p-3.5 pl-4 text-[13px] leading-relaxed italic text-[#8a8a92]"
                        style={{ background: 'rgba(96,165,250,0.05)', borderLeft: `2px solid ${C.blue}`, borderRadius: '0 10px 10px 0' }}
                      >
                        <span className="text-[22px] align-[-4px] mr-1" style={{ color: C.blue }}>"</span>
                        {s.reasoning}
                        <span className="block not-italic font-sans text-[11px] tracking-[0.18em] uppercase text-[#5b5b62] mt-2">{s.ref}</span>
                      </div>

                      {/* Score bars */}
                      <div className="grid grid-cols-2 gap-4 mt-4">
                        {[
                          { label: 'Embedding similarity', val: s.embedding_score },
                          { label: 'DNA compatibility',    val: s.dna_score },
                        ].map(b => (
                          <div key={b.label}>
                            <div className="flex justify-between text-[12px] mb-1.5">
                              <span className="text-[#5b5b62]">{b.label}</span>
                              <span className="text-[#8a8a92]">{b.val.toFixed(2)}</span>
                            </div>
                            <div className="h-1 rounded-full bg-white/[0.06]">
                              <div className="h-full rounded-full" style={{ width: `${b.val * 100}%`, background: '#ededee', opacity: 0.5 }} />
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Scoreboard */}
                    <div className="text-right min-w-[110px] flex-shrink-0">
                      <div className="text-[10px] text-[#8a8a92] tracking-[0.22em] uppercase">Combined</div>
                      <div className="font-fraunces font-light text-[44px] leading-none tracking-[-0.02em] my-1" style={{ color }}>
                        {s.combined_score.toFixed(2)}
                      </div>
                      <div className="flex flex-col gap-1.5 items-end">
                        <button
                          onClick={() => handleApprove(s.mentor_id, s)}
                          disabled={!!approving}
                          className="w-[110px] h-8 rounded-full text-[12px] font-medium border-0 cursor-pointer transition-colors disabled:opacity-60"
                          style={s.isBest
                            ? { background: '#ededee', color: '#0b0b0c' }
                            : { background: 'transparent', color: '#8a8a92', border: '1px solid #232327' }
                          }
                          onMouseEnter={e => { if (!s.isBest) { e.currentTarget.style.color = '#ededee'; e.currentTarget.style.borderColor = '#3a3a40' } else { e.currentTarget.style.background = '#fff' } }}
                          onMouseLeave={e => { if (!s.isBest) { e.currentTarget.style.color = '#8a8a92'; e.currentTarget.style.borderColor = '#232327' } else { e.currentTarget.style.background = '#ededee' } }}
                        >
                          {approving === s.mentor_id ? 'Approving…' : 'Approve'}
                        </button>
                        <button
                          className="w-[110px] h-8 rounded-full text-[12px] font-medium text-[#5b5b62] hover:text-[#8a8a92] border border-[#232327] hover:border-[#3a3a40] transition-colors cursor-pointer bg-transparent"
                        >
                          Details
                        </button>
                      </div>
                    </div>
                  </div>
                </article>
              )
            })}
          </section>
        </div>
      </main>
    </div>
  )
}
